[bans]
multiple-versions = "deny"
skip-tree = [
    { name = "axum" },           # TODO: Need to upgrade to latest tonic
    { name = "hashbrown" },
    { name = "heck" },
    { name = "itertools" },
    { name = "rand" },           # Waiting for alloy and other crates to upgrade to 0.9+
    { name = "regex-automata" }, # Waiting for matchers crate to upgrade
    { name = "rustix" },
    { name = "thiserror" },
    { name = "webpki-roots" },   # No actual duplication, as v0 package was made to depend on v1
]

# We should always specify version ranges
wildcards = "deny"

deny = [
    { name = "openssl-sys", reason = "We use rustls throughout the project" },
    { name = "native-tls", reason = "We use rustls throughout the project" },
]

[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MIT-0",
    "OpenSSL",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
private = { ignore = true }


[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-org = { github = ["kamu-data"] }


[advisories]
yanked = "deny"
ignore = [
    # dotenv is Unmaintained
    # https://rustsec.org/advisories/RUSTSEC-2021-0141
    "RUSTSEC-2021-0141",
    # paste - no longer maintained
    # https://rustsec.org/advisories/RUSTSEC-2024-0436
    "RUSTSEC-2024-0436",
]
