[bans]
multiple-versions = "deny"

# We should always specify version ranges
wildcards = "deny"


[licenses]
allow = [
    "0BSD",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MIT-0",
    "MPL-2.0",
    "OpenSSL",
    "Unicode-3.0",
    "Unlicense",
    "Zlib",
]
private = { ignore = true }


[sources]
unknown-git = "deny"
unknown-registry = "deny"


[advisories]
yanked = "deny"
ignore = []
